### PR TITLE
Fixing Issue

### PR DESCRIPTION
**Pull request by knightoftheshadows**
Now it works with machines without terminal.

### CODE REVIEW

**Comment by deepjyoti30** [comment]
Fixes #13 

Adding so that users can know this is the fix of that issue

**Comment by deepjyoti30** [comment]
@knightoftheshadows Thanks for the PR.

I will take a proper look at the code soon. However, one thing I need to point out is that the traceback code is not necessary in the packages, it's useful for debugging but let's not show the user a traceback.

This can be discussed upon. If you want, you can open an issue to discuss to make this traceback optional but that would be a whole different patch.

At the moment, I don't think adding tracebacks is necessary while showing the users the error.

**Comment by ChanceNCounter** [comment]
Log it, maybe?

**Comment by deepjyoti30** [comment]
@ChanceNCounter That's the plan, however, considering the size of the package, I am not sure if adding that would be a great idea because that might add some bulk.

**Comment by deepjyoti30** [comment]
@ChanceNCounter @knightoftheshadows Added a separate patch for #13 .

The download function is already pretty complex so rather than adding more `if's`, just added a default value for the terminal size. So if the `--quiet` flag is passed then this default value will be used.

Closing this issue.

**Pull request closed without merging**
