### PR TITLE
Not-really-a-refactor to accomodate shell scripts

### PR DESCRIPTION
**Pull request by ChanceNCounter**
And assorted other things. I probably shouldn't have squashed all this, but here it is. Also, I haven't written tests, nor have I tried resuming an interrupted download, so I might have broken that. It's a lot of change, and certainly a big departure from what you posted, so feel free to dismiss this =)

Furthermore, I don't really work with the shell. I just wanted to be able to shove this in a pipeline. This might be a kludge, it might be bad code, it might be an abuse of stderr, it might be naive and inefficient. I really wouldn't know.

(Commits are yours MIT.)

-------
Changes:
* New arguments
  - `--echo` redirects output to stderr, then prints the filepath to stdout
after downloading is finished. This can be piped to
other commands/programs that take input from stdout, including xargs:
        `dw -e <url> | xargs -o vim`
  - `-q, --quiet` squelches most output
* More descriptive help, because there are now twice as many arguments
* Accidental pep8 (thanks VSCode) except autopep8 isn't respecting
line length
* Moved "resume download" into a flag for safety reasons
* Pass arguments to Downloader explicitly

### CODE REVIEW

**Comment by ChanceNCounter** [comment]
I'd also posit that it probably shouldn't return 0 on keyboard interrupt, but I didn't make that change.

**Comment by deepjyoti30** [comment]
Hey @ChanceNCounter , I'll review the PR later today.

**Comment by ChanceNCounter** [comment]
Cool. I forgot to explain that the "safety reason" is to protect small files: since the check for an incomplete download is based on filesize, I was concerned about clobbering a smaller file with a larger one.

**Comment by deepjyoti30** [comment]
Yeah I think the ```--continue-download``` is a required option.

**Pull request merged**
